services:
  - type: web
    name: doxarealm-cms
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: chmod +x ./start.sh && ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: doxarealm-postgres
          property: connectionString

databases:
  - name: doxarealm-postgres
    plan: free
    databaseName: doxarealm_db
    user: doxarealm_user
